service: express-sls-app-with-stitch

custom:
  secrets: ${file(secrets.json)}

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${self:custom.secrets.NODE_ENV}
  region: eu-central-1
  environment: 
    NODE_ENV: ${self:custom.secrets.NODE_ENV}
    STITCH_APP_ID: ${self:custom.secrets.STITCH_APP_ID}
    DB_NAME: ${self:custom.secrets.DB_NAME}
    DB_URL: ${self:custom.secrets.DB_URL}

functions:
  app:
    handler: server.run
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

plugins:
  - serverless-offline